### ISSUE TITLE
Filter out types returned to only ComputationalTool and Dataset

### ISSUE THREAD

**Issue by flaneuse** [NIAID-Data-Ecosystem/nde-discovery-api#1]
Within the NIAID Data Ecosystem API, add a custom QueryBuilder to filter out any records where `@type` is not `Dataset` or `ComputationalTool`.  This will be the equivalent of running [this query](https://api.data.niaid.nih.gov/v1/query?q=@type:Dataset%20OR%20@type:ComputationalTool&facets=@type&size=0) by default on every single query, before the user-specified query is run.

NOTE: we should ensure that all `Software` or `SoftwareSourceCode` types are converted to `ComputationalTool` within the individual crawling scripts.

Examples:
https://github.com/data2health/resource-discovery-api/blob/main/web/pipeline.py
https://github.com/biothings/mygene.info/blob/master/src/web/pipeline/build.py
https://docs.biothings.io/en/latest/tutorial/web.html

**Comment by jal347** [comment]
Other examples: https://github.com/SmartAPI/smartAPI/blob/0.10.x/src/pipeline.py
