### ISSUE TITLE
[ES scoring change] Upweight Resource Catalogs relative to Datasets

### ISSUE THREAD

**Issue by gtsueng** [NIAID-Data-Ecosystem/nde-discovery-api#15]
### Issue Name
Upweight Resource Catalogs relative to Datasets

### Issue Description
The NIAID team would like to see Resource Catalogs appear at the top of a search result list, IF the search result list includes a Resource Catalog. This can be accomplished by boosting the weight of Resource Catalogs in an ES search. However, we don't want to boost it to the point that it comes up even if it is barely relevant to the search term.

Note that this issue may potentially be inadvertently addressed/affected by the application of the Metadata Completeness score, so it may need to be tweaked after the application of the Metadata Completeness score has been determined.

### Issue Discussion
This issue was discussed at the ODSET Onsite meeting dated 2024.03.06

### Related WBS task
https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues/18
https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues/2

**Comment by gtsueng** [comment]
@jal347 The NIAID team has approved a few resource catalogs to move forward to production. Please adjust the ES search rankings such that IF a ResourceCatalog is included in a search result, it goes to the top of the search results.

**Comment by gtsueng** [comment]
@jal347 Can you look into why the boosting works for: https://data.niaid.nih.gov/search?q=%22Tuberculosis%22
![Image](https://github.com/NIAID-Data-Ecosystem/nde-discovery-api/assets/9200138/c8b1dff1-f833-4535-a5fb-8c13cd8ca8e5)

 

but not for:
https://data.niaid.nih.gov/search?q=%22Tuberculosis%22+OR+%22Mycobacterium+bovis%22+OR+%22Mycobacterium+africanum%22+OR+%22Mycobacterium+canetti%22+OR+%22Mycobacterium+microti%22+OR+%22Phthisis%22
![Image](https://github.com/NIAID-Data-Ecosystem/nde-discovery-api/assets/9200138/909a2cab-67e0-40ce-80f5-4966789d567c)

**Comment by jal347** [comment]
@gtsueng Its fixed now. I couldn't find any issue with it so I just made the boosting from 10 to 100 and it worked. 


<img width="1642" alt="Screenshot 2024-06-26 at 4 48 51 PM" src="https://github.com/NIAID-Data-Ecosystem/nde-discovery-api/assets/35415519/3ea60dee-904a-46aa-a7d7-eaf6b3b9f96d">

**Comment by gtsueng** [comment]
great!
